import type { Metadata } from "next";
import Link from "next/link";
import { BookOpenCheck, Database, ExternalLink, Scale, ShieldCheck } from "lucide-react";
import { PrototypeShell } from "@/components/prototype-shell";
import { genLayerGameConfig } from "@/lib/genlayer-game";

export const metadata: Metadata = { title: "Integrity · MEG", description: "The MEG trust model and Studio Next resolution path." };

export default function IntegrityPage() { return <PrototypeShell title="Know what decides your payout." intro="The interface helps you read the board. Registered sources, GenLayer consensus, and deterministic contract state decide the money."><section className="rules-list"><article><span>01</span><div className="rule-icon"><Database size={17} /></div><div><strong>Immutable entry</strong><p>The nine options and gross stake are stored by the MEG game contract after wallet acceptance. Neither the frontend nor owner can rewrite a player’s grid.</p></div></article><article><span>02</span><div className="rule-icon"><BookOpenCheck size={17} /></div><div><strong>Approved sources before lock</strong><p>A registered round carries its evidence URLs before entries open. The resolver reads public text only; it does not interpret video for this MVP.</p></div></article><article><span>03</span><div className="rule-icon"><Scale size={17} /></div><div><strong>Consensus before settlement</strong><p>Validators independently compare the registered evidence and persist a strict result for all nine cells before the settlement transaction can continue.</p></div></article><article><span>04</span><div className="rule-icon"><ShieldCheck size={17} /></div><div><strong>Recovery is part of the lifecycle</strong><p>Missing evidence, unplayed maps, underfilled rounds, cancellations, and timeouts preserve refund paths. A cell does not silently become a loss.</p></div></article></section><section className="proof-stack"><div className="notice-strip"><ShieldCheck size={15} /><span>Current public network: <strong>{genLayerGameConfig.networkLabel}</strong>. MEG supports Studio Next for public play and Localnet only for automated development tests.</span></div><Link className="text-link" href="/genlayer">Inspect the proof surface <ExternalLink size={14} /></Link><span className="text-link">Public source and deployment evidence are available for review.</span></section></PrototypeShell>; }
